In [1]:
import pyranges as pr
import pandas as pd

In [2]:
def get_vars_by_gene(var_mac_df, gene_id, gene_annotation, padding = 0):
    split_var_names = var_mac_df.columns[1:].to_series().str.split(":", expand=True)
    variants = pr.from_dict({
        "Chromosome":split_var_names[0].astype(str), 
        "Start":split_var_names[1].astype(int), 
        "End":split_var_names[1].astype(int)+1,
        "var_name":split_var_names.index
    })
    
    gene_annotation_expanded = gene_annoation.copy()
    gene_annotation_expanded.Start = gene_annotation_expanded.Start - padding
    gene_annotation_expanded.End = gene_annotation_expanded.End + padding
    
    included_vars = variants.intersect(gene_annotation_expanded[gene_annotation_expanded.gene_id.str.startswith(gene_id)])
    included_vars = included_vars.as_df()["var_name"].to_list() if included_vars else []
    return var_mac_df[["ID"]+included_vars]

In [3]:
mac_index_vars = pd.read_parquet("/s/project/uk_biobank/processed/clumping/30780/WES_200K_index_vars_mac_30780.parquet.p")
gtf_file = "/s/genomes/Gencode/Gencode_human/release_34/gencode.v34.annotation.gtf.gz"
#gtf_file = "/s/genomes/Gencode/Gencode_human/release_34/GRCh37_mapping/gencode.v34lift37.annotation.gtf.gz"
genome_annotation = pr.read_gtf(gtf_file)
gene_annoation = genome_annotation[genome_annotation.Feature=="gene"]

In [4]:
get_vars_by_gene(mac_index_vars, "ENSG00000084674", gene_annoation, padding = 150000)

,ID,chr2:21001981:C>T,chr2:21002482:T>C,chr2:21002881:C>T,chr2:21004631:T>C,chr2:21005467:A>T,chr2:21005955:C>T,chr2:21006196:G>A,chr2:21006288:C>T,chr2:21006574:G>C,...,chr2:21023510:C>G,chr2:21026844:C>T,chr2:21028042:G>A,chr2:21029883:A>G,chr2:21033533:G>C,chr2:21033534:T>G,chr2:21033617:A>T,chr2:21037264:G>A,chr2:21042269:C>A,chr2:21043902:GGCAGCGCCA>G
0,-000001,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,1
1,-000002,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,2,0
2,-000003,0,0,1,0,0,0,0,0,0,...,0,1,2,0,0,0,0,0,1,0
3,-000004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,-000005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200638,6026083,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
200639,6026120,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
200640,6026143,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,2,0
200641,6026179,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
200642,6026184,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0